[workspace]
resolver = "2"
members = ["crates/xpict-core"]
default-members = ["crates/xpict-core"]

[workspace.package]
edition = "2021"
license = "MIT"
repository = "https://github.com/swamidasslab/xenosite-pict"
rust-version = "1.75"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
