"""Type stubs for the Rust extension ``xpict._native``."""

__version__: str

BOND_PX: float
OFFSET_PX: float
STROKE_PX: float
SHADE_FRAC: float
HAS_ELK: bool
HAS_GEOM: bool
HAS_FONT: bool

class Shape:
    @staticmethod
    def empty() -> Shape: ...
    @staticmethod
    def from_ring(ring: list[tuple[float, float]]) -> Shape: ...
    @staticmethod
    def from_contours_evenodd(contours: list[list[tuple[float, float]]]) -> Shape: ...
    @staticmethod
    def disk(cx: float, cy: float, radius: float, quad_segs: int = 12) -> Shape: ...
    @staticmethod
    def capsule(x1: float, y1: float, x2: float, y2: float, radius: float) -> Shape: ...
    @staticmethod
    def polyline_buffer(pts: list[tuple[float, float]], radius: float) -> Shape: ...
    @staticmethod
    def multipoint_buffer(pts: list[tuple[float, float]], radius: float) -> Shape: ...
    @staticmethod
    def annular(cx: float, cy: float, r: float, stroke_width: float) -> Shape: ...
    @property
    def is_empty(self) -> bool: ...
    @property
    def area(self) -> float: ...
    @property
    def bounds(self) -> tuple[float, float, float, float] | None: ...
    @property
    def centroid(self) -> tuple[float, float] | None: ...
    @property
    def has_holes(self) -> bool: ...
    @property
    def point_count(self) -> int: ...
    def buffer(self, dist: float) -> Shape: ...
    def halo(self, dist: float) -> Shape: ...
    def simplify(self) -> Shape: ...
    def union(self, other: Shape) -> Shape: ...
    def difference(self, other: Shape) -> Shape: ...
    def xor(self, other: Shape) -> Shape: ...
    def translate(self, dx: float, dy: float) -> Shape: ...
    def scale(self, sx: float, sy: float, ox: float = 0.0, oy: float = 0.0) -> Shape: ...
    def contains(self, x: float, y: float) -> bool: ...
    def to_svg_d(self) -> str: ...
    def horizontal_span_at(self, y: float) -> float: ...
    def polygons(
        self,
    ) -> list[tuple[list[tuple[float, float]], list[list[tuple[float, float]]]]]: ...
    def __bool__(self) -> bool: ...

def multi_bond_offset(length: float) -> float: ...
def centered_displacements(order: float, off: float) -> list[float]: ...
def depict_molecule(molecule_json: str) -> str: ...
def validate_edge_plan(plan_json: str) -> str: ...
def plan_edge(spec_json: str) -> str: ...
def render_doc(spec_json: str, edge_json: str) -> str: ...
def element_symbol(z: int) -> str: ...
def atomic_number(symbol: str) -> int | None: ...
def kabsch_2d(
    src: list[tuple[float, float]],
    dst: list[tuple[float, float]],
    allow_reflect: bool = True,
) -> tuple[float, float, float, float, float]: ...
def rigid_align_coords(
    template: list[tuple[int, float, float]],
    other: list[tuple[int, float, float]],
    mapping: list[tuple[int, int]],
) -> list[tuple[int, float, float]]: ...
def plotdot_rings(z: float, levels: int = 4) -> list[tuple[float, float]]: ...
def plotdot_disks(
    zs: list[float], coords: list[tuple[float, float]], levels: int = 4
) -> list[tuple[float, float, float, float]]: ...
def capsule_halo_path_d(
    x1: float,
    y1: float,
    x2: float,
    y2: float,
    ink_radius: float,
    grow: float,
) -> str | None: ...
def disk_halo_path_d(cx: float, cy: float, ink_radius: float, grow: float) -> str | None: ...
def elk_layout_json(graph_json: str) -> str: ...
def face_metrics(
    style: str = "regular",
) -> tuple[float, float, float, float, float, float, float]: ...
def glyph_metrics(
    ch: str, style: str = "regular"
) -> tuple[float, tuple[float, float, float, float] | None]: ...
def outline_run_em(text: str, style: str = "regular") -> tuple[Shape | None, float]: ...
def compile_text_shapes(
    text: str,
    x: float,
    y: float,
    font_size: float,
    anchor: str = "middle",
    style: str = "regular",
) -> Shape | None: ...
def place_backbone(
    atoms: list[tuple[float, float, str | None]],
    bonds: list[tuple[int, int]],
    font_size: float | None = None,
    weight: float = 1.0,
) -> tuple[
    list[tuple[float, float, float, float]],
    list[tuple[str, float, float, float, float, str, float, str, str] | None],
]: ...
def split_atom_label(raw: str) -> tuple[str, str]: ...
def compose_atom_label(center: str, traveling: str, side: str) -> str: ...
def label_ink_shape(
    raw: str,
    origin_x: float,
    y: float,
    atom_x: float,
    atom_y: float,
    side: str,
    font_size: float | None = None,
) -> Shape | None: ...
